name: Build

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build-linux:
    strategy:
      matrix:
        GOARCH: ['amd64', '386']
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - run: |
        sudo apt-get install gcc-multilib g++-multilib
        mkdir -p dist
        go build -o dist/hdb-linux-$GOARCH
      env:
        GOARCH: ${{ matrix.GOARCH }}
        CGO_ENABLED: 1
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: dist-linux
        path: dist/hdb-linux-*
  build-windows:
    strategy:
      matrix:
        GOARCH: ['amd64', '386']
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - run: |
        mkdir -p dist
        go build -o dist/hdb-windows-$GOARCH.exe
      env:
        GOARCH: ${{ matrix.GOARCH }}
        CGO_ENABLED: 1
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: dist-windows
        path: dist/hdb-windows-*
